services:
  code-adviser-server:
    build: .
    ports:
      - "8085:8080"
    environment:
      CODE_ADVISER_DATASOURCE_URL: jdbc:postgresql://code-adviser-postgres:5432/${CODE_ADVISER_DB_NAME}
      CODE_ADVISER_DATASOURCE_USERNAME: ${CODE_ADVISER_DATASOURCE_USERNAME}
      CODE_ADVISER_DATASOURCE_PASSWORD: ${CODE_ADVISER_DATASOURCE_PASSWORD}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      OPEN_AI_AUTHORIZATION_TOKEN: ${OPEN_AI_AUTHORIZATION_TOKEN}

  code-adviser-postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: ${CODE_ADVISER_DB_NAME}
      POSTGRES_USER: ${CODE_ADVISER_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${CODE_ADVISER_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
