spring:
  application:
    name: code-adviser

  datasource:
    url: ${CODE_ADVISER_DATASOURCE_URL}
    username: ${CODE_ADVISER_DATASOURCE_USERNAME}
    password: ${CODE_ADVISER_DATASOURCE_PASSWORD}
  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    token:
      expire-after: 1h

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  cloud:
    openfeign:
      client:
        config:
          open-ai:
            url: ${code-adviser.open-ai.url}
            connectTimeout: 60000
            readTimeout: 60000

code-adviser:
  open-ai:
    url: https://api.openai.com/v1/chat/completions
    token: ${OPEN_AI_AUTHORIZATION_TOKEN}
    default-settings:
      model: gpt-4o
      temperature: 1
      n: 1
      role: user
